:scheduler:
  :schedule:
    unread_messages_notifier_worker:
      cron: "*/30 * * * *"
      class: "UnreadMessagesNotificationWorker"
      queue: default
    delete_archive_chats_worker:
      cron: "0 0 * * *"
      class: "DeleteArchiveChatsWorker"
      queue: default
